name: MakeMO

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step per il checkout del repository
      - uses: actions/checkout@v2

      # Step per generare i file .mo da .po
      - name: Create MO files
        run: |
          sudo apt-get -q update
          sudo apt-get install gettext
          mkdir -p Rel
          for f in $(ls -1 po/*.po | sed -e 's/\.po$//' | sed 's/.*\///'); do
            msgfmt -o Rel/$f.mo po/$f.po
          done;

      # Step per commettere e fare il push dei file .mo generati sul branch 'main'
      - name: Commit and push .mo files to main branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add Rel/*
          git commit -m "Add .mo files"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/formiano/enigma2.po.git --force origin main

