jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Create .mo files
        run: |
          sudo apt-get -q update
          sudo apt-get install gettext
          mkdir Rel
          for f in $(ls -1 po/*.po | sed -e 's/\.po$//' | sed 's/.*\///'); do
            msgfmt -o Rel/$f.mo po/$f.po
          done;

      - name: Commit and push .mo files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add Rel/*
          git commit -m "Add .mo files"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/formiano/enigma2.po.git --force gh-pages

