name: MakeMO

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: create mo
        run: |
          sudo apt-get -q update
          sudo apt-get install gettext
          mkdir Rel
          for f in $(ls -1 po/*.po | sed -e 's/\.po$//' | sed 's/.*\///');do msgfmt -o Rel/$f.mo po/$f.po; done;

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Rel
          force_orphan: true
